---
- name: Run Unit Tests ({{ build_type }})
  command: "{{ build_dir}}/tests/unit-tests/unit-tests"

- name: Run Smoke Tests ({{ build_type }})
  command: make run-smoke-tests
  args:
    chdir: "{{ build_dir }}"

- name: Run Integration Tests ({{ build_type }})
  command: make run-integration-tests
  args:
    chdir: "{{ build_dir }}"

- name: Run End2End Tests ({{ build_type }})
  command: make run-end2end-tests
  args:
    chdir: "{{ build_dir }}"

# - name: Drop CMakeCache for Ocular tests ({{ build_type }})
#   ansible.builtin.file:
#     path: "{{ build_dir }}/CMakeCache.txt"
#     state: absent

# - name: Regenerate Build System for Ocular tests ({{ build_type }})
#   command: cmake -DPATH_TO_LLVM={{ llvm_dir }} -DPATH_TO_OCULAR={{ ocular_dir }} -DCMAKE_BUILD_TYPE={{ build_type }} -DCMAKE_CXX_FLAGS="{{ llvm2cpg_cxx_flags }}" {{ source_dir }}
#   args:
#     chdir: "{{ build_dir }}"
#   environment:
#     CC: "{{ llvm_dir }}/bin/clang"
#     CXX: "{{ llvm_dir }}/bin/clang++"

# - name: Run End2End Tests ({{ build_type }})
#   command: make run-end2end-tests
#   args:
#     chdir: "{{ build_dir }}"
