- name: Ubuntu CI
  hosts: "{{ host | default('all') }}"

  vars:
    platform: ubuntu

    llvm2cpg_cxx_flags: -D_GLIBCXX_USE_CXX11_ABI=1

    packages:
      - vim
      - wget
      - git
      - ninja-build
      - libz-dev
      - ncurses-dev
      - libstdc++6
      - pkg-config
      - libxml2-dev
      - binutils
      - unzip
      - sbt
      - openjdk-8-jdk
      - openjdk-8-jre
      - python3
      - python3-pip
      - python3-pkg-resources

    python_packages:
      - lit
      - filecheck

  vars_files:
    - helpers/variables.yaml

  tasks:
    - name: Prepare Working Directory
      include: helpers/working-dir.yaml

    - name: Add sbt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      become: true

    - name: Add sbt repo
      apt_repository:
        repo: "deb https://dl.bintray.com/sbt/debian /"
        state: present
      become: true

    - name: Install Required Packages
      apt:
        name: "{{ packages }}"
        state: present
      become: true

    - name: Install Python packages
      pip:
        name: "{{ python_packages }}"
        state: present
        executable: pip3

    - name: Download CMake
      get_url:
        url: https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.sh
        dest: "{{ working_dir }}/cmake.sh"
      register: download_cmake

    - name: Install CMake
      shell: sh {{ working_dir }}/cmake.sh --prefix=/usr/local --skip-license
      args:
        creates: /usr/local/bin/cmake
      when: download_cmake.changed
      become: true

    - name: Install Ocular
      include: helpers/install-ocular.yaml

    - name: Install Joern
      include: helpers/install-joern.yaml

    - name: Install LLVM
      include: helpers/install-llvm.yaml

    - name: Install Protobuf
      include: helpers/install-protobuf.yaml

    - name: Install Libzip
      include: helpers/install-libzip.yaml

    - name: Build and test
      include: helpers/build-and-test.yaml

    - name: Package
      include: helpers/package.yaml
