name: CI Ubuntu 18.04

env:
  LLVM_RELEASE: "9.0"
  OCULAR_ORG_ID: ${{ secrets.OCULAR_ORG_ID }}
  OCULAR_ORG_PASSWORD: ${{ secrets.OCULAR_ORG_PASSWORD }}

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "**"

jobs:
  test:
    name: LLVM ${{ matrix.LLVM_VERSION }}
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    strategy:
      matrix:
        LLVM_VERSION: ["9.0"]

    steps:
      - name: Install software
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository ppa:git-core/ppa
          apt-get update && apt-get install -y python-pip curl git
          pip install ansible
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run CI task
        run: |
          cd ci && ansible-playbook ubuntu-playbook.yaml \
            -e source_dir=$PWD/.. \
            -e gitref=$GITHUB_SHA \
            -e llvm_version="${{ matrix.LLVM_VERSION }}.0" \
            -e host=localhost \
            --verbose
      - name: Attach package to the tag
        if: matrix.LLVM_VERSION == env.LLVM_RELEASE && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/packages/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true


